#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config external_bar off:26:0

# global settings
#yabai -m config                                 \
#   external_bar                 off:40:0       \
#    menubar_opacity              1.0            \
#    display_arrangement_order    default        \
#    window_origin_display        default        \
#    window_zoom_persist          on             \
#    window_shadow                on             \
#    window_animation_easing      ease_out_circ  \
 #   insert_feedback_color        0xffd75f5f     \


yabai -m config mouse_follows_focus             on
yabai -m config focus_follows_mouse             autoraise
yabai -m config window_placement                second_child
yabai -m config window_topmost                  off
yabai -m config window_shadow                   off
yabai -m config window_border                   off
yabai -m config window_border_placement         exterior
yabai -m config window_border_width             10
yabai -m config window_border_radius            0
yabai -m config active_window_border_color      0xB2EBDBB2
yabai -m config normal_window_border_color      0xB2282828
yabai -m config insert_window_border_color      0xB2EBDBB2
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_opacity                  off
yabai -m config split_ratio                     0.50
yabai -m config auto_balance                    on
yabai -m config mouse_modifier                  fn
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize
yabai -m config mouse_drop_action               swap
yabai -m window_animation_duration               0
yabai -m config window_opacity_duration         0.25
yabai -m split_type                            auto


# general space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     0
yabai -m config bottom_padding                 0
yabai -m config left_padding                    0
yabai -m config right_padding                   0
yabai -m config window_gap                      0

# Space labels
yabai -m space 1 --label "Free"
yabai -m space 2 --label "Browse"
yabai -m space 3 --label "Code"
yabai -m space 4 --label "Terminal"
yabai -m space 5 --label "Mail/Calendar"
yabai -m space 6 --label "Notes"
yabai -m space 7 --label "Social"
yabai -m space 8 --label "Media"
yabai -m space 9 --label "Float"

# Space config
yabai -m config --space 9 layout float

yabai -m rule --add app="Firefox\ Nightly"               space=2
yabai -m rule --add app="^Code$"                space=3
yabai -m rule --add app="IntelliJ$"                space=3
yabai -m rule --add app="kitty"     space=4
yabai -m rule --add app="Spotify"               space=8




echo "yabai configuration loaded.."
