[manager]
show_hidden = true
sort_by     = "natural"
sort_sensitive = false
sort_dir_first = true
linemode = "size_and_mtime"
show_symlink = true

[preview]
tab_size   = 2
max_width  = 1000
max_height = 1000

[plugin]
prepend_preloaders = [
    # HEIC preloader
    { mime = "image/heic", run = "heic" },
]